on: [push]
name: ARM deployment

env:
  AZURE_RESOURCE_GROUP: github-action
  TEMPLATE_FILE: ./azuredeploy.json
  PARAMETERS_FILE: ./parameters.json

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

#    - uses: azure/CLI@v1
#      with:
#        azcliversion: latest
#        inlineScript: |
#          az deployment group create --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --template-file ${{ env.TEMPLATE_FILE }} --parameters ${{ env.PARAMETERS_FILE }}

    - uses: whiteducksoftware/azure-arm-action-js@v2
      with:
        resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP }}
        templateLocation: ${{ env.TEMPLATE_FILE }}
        parameters: ${{ env.PARAMETERS_FILE }}

